### ISSUE TITLE
On IE10, abort function is failed disposing player with hls plugin

### ISSUE THREAD

**Issue by t2y** [videojs/video.js#1556]
I encountered only IE10. This error is not reproduced on IE11, Chrome35 and Firefox31. My environment is here.

* videojs-4.9.0
* videojs-swf-4.5.0
* videojs-contrilb-hls-plugin-0.9.1
* videojs-contrib-media-source-0.3.0

```
Error
   at Anonymous function (Unknown script code:49:5)
   at abort (http://hostname/js/video-js/videojs-media-sources.js:215:7)
   at dispose (http://hostname/js/video-js/videojs.hls.js:253:5)
   at dispose (http://hostname/js/video-js/video.dev.js:3486:20)
   ... 
VIDEOJS:Error 
SCRIPT16389: Unspecified error.
video.dev.js, line 3952 
```
It seems SCRIPT16389 menas JavaScript Run-time Errors.
http://msdn.microsoft.com/library/ie/1dk3k160%28v=vs.94%29.aspx

**Comment by gkatsev** [comment]
If this is still an issue, it should probably move to the contrib-hls project.
