### ISSUE TITLE
Flash tech isn't working on chrome OSX

### ISSUE THREAD

**Issue by shaharmor** [videojs/video.js#2446]
Hi,

When using the Flash tech were getting errors in the console and the video isn't playing.
We updated to latest 4.12.12 version and hls 0.17.6 but still no good

```javascript
videojs-media-sources.js:186 Uncaught TypeError: self.source.swfObj.CallFunction is not a function
video.dev.js:1457 VIDEOJS: Video.js: buffered unavailable on Hls playback technology element. TypeError: this.el_.vjs_getProperty is not a function
    at vjs.Flash.buffered (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:7953:42)
    at vjs.Player.techGet (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4322:31)
    at vjs.Player.buffered (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4474:23)
    at vjs.Player.bufferedPercent (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4495:23)
    at vjs.Player.onProgress (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4216:12)
    at HTMLDivElement.ret (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:885:15)
    at HTMLDivElement.data.dispatcher (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:360:29)
    at Function.vjs.trigger (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:605:25)
    at vjs.Component.trigger (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:2503:7)
    at XMLHttpRequest.<anonymous> (https://s3.amazonaws.com/github-cloud/releases/14029328/97ee1012-0e12-11e5-…IJMK3TQ&Expires=1438949564&Signature=RBbTM17zfBTwl54jP8fWFGA5duU%3D:3:8687)
video.dev.js:4336 Uncaught TypeError: this.el_.vjs_getProperty is not a function
```

**Comment by mmcc** [comment]
The Flash tech is [working fine](http://output.jsbin.com/himeve) in Chrome 44 on OS X 10.10.3. This issue is probably better suited for the media-sources plugin's issue tracker.

**Comment by shaharmor** [comment]
Well, the link you posted isn't working.
I'm using Chrome version 44.0.2403.130 (64-bit) on OSX 10.10.4, and i'm getting the following error:

```javascript
video.js:24 VIDEOJS: TypeError: this.c.vjs_play is not a function
    at s.play (http://vjs.zencdn.net/4.12/video.js:139:316)
    at N (http://vjs.zencdn.net/4.12/video.js:68:80)
    at s.play (http://vjs.zencdn.net/4.12/video.js:68:411)
    at t.rb.u (http://vjs.zencdn.net/4.12/video.js:109:331)
    at HTMLDivElement.e (http://vjs.zencdn.net/4.12/video.js:14:285)
    at HTMLDivElement.t.b.e.ba.e.ba (http://vjs.zencdn.net/4.12/video.js:7:288)
video.js:139 Uncaught TypeError: this.c.vjs_play is not a functions.play @ video.js:139N @ video.js:68s.play @ video.js:68t.rb.u @ video.js:109e @ video.js:14t.b.e.ba.e.ba @ video.js:7
```

**Comment by mmcc** [comment]
Hate to say this, but that seems very much specific to you. Just tested on 3 other OS X machines in the office, all fine.

My setup specifically is almost identical to yours. 
- Exact same version of Chrome: Version 44.0.2403.130 (64-bit)
- One patch version behind in OS X (10.10.3), but also tested on 10.10.4 machine without issue.

Are you sure everything's ok with your Flash installation?

**Comment by shaharmor** [comment]
It worked just a few days ago.
Its working perfectly on Firefox.
Other flash players are working as well.
It seems to be related to this maybe: #2247

**Comment by mmcc** [comment]
I don't know what to tell you other than if that JSBin I linked to isn't working, this is almost certainly a problem with your environment.

**Comment by gkatsev** [comment]
Do you have flash disabled in chrome? Or is flash running in power saving mode? In either of those cases you could get issues with flash.

**Comment by shaharmor** [comment]
It seems that if the FlashBlock extensions is running, even though its set to OFF for this page, its messing up flash and causes those issues. Disabling the extension fixes the issue.

**Comment by benwilber** [comment]
I can confirm that videojs HLS and Dash plugins fail (or work very intermittently) if a flash-blocking extension is installed and enabled, even if flash is allowed on the page.  You must disable the extension completely in order to get flash-based plugins to work.  Is the Flash fallback being loaded/used in some tricky non-standard way and possibly causing this?  I've been using Flash block/Flashcontrol forever and I've never seen anything like this.

**Comment by heff** [comment]
It's the difference between a check for if the Flash is supported or if Flash is going to be blocked. Video.js can only check if Flash is supported, so if it sees `true` it's going to attempt to play Flash and not fallback.
