### ISSUE TITLE
use vjs、ads、hls

### ISSUE THREAD

**Issue by writethesky** [videojs/video.js#2451]
if my code:
```javascript
<script src="core/video.js"></script>
<script src="core/lang/zh-CN.js"></script>
<script src="media-sources.js"></script>
<script src="hls.min.js"></script>
<script src="videojs.ads.js"></script>

```
the browser throw err :
```javascript
VIDEOJS: Error: Error: An invalid exception was thrown.
    at Error (native)
    at s.play (http://127.0.0.1/player/core/video.js:139:316)
    at b.Hls.play (http://127.0.0.1/player/hls.min.js:3:4251)
    at N (http://127.0.0.1/player/core/video.js:68:80)
    at s.play (http://127.0.0.1/player/core/video.js:68:411)
    at t.rb.u (http://127.0.0.1/player/core/video.js:109:331)
    at HTMLDivElement.e (http://127.0.0.1/player/core/video.js:14:285)
    at HTMLDivElement.t.b.e.ba.e.ba (http://127.0.0.1/player/core/video.js:7:288)

```
but the video can continue to play

if my code:
```javascript
<script src="core/video.dev.js"></script>
<script src="core/lang/zh-CN.js"></script>
<script src="media-sources.js"></script>
<script src="hls.min.js"></script>
<script src="videojs.ads.js"></script>

```
the browser throw err :
```javascript
VIDEOJS: Error: Error: An invalid exception was thrown.
    at Error (native)
    at vjs.Flash.play (http://127.0.0.1/player/core/video.dev.js:7927:12)
    at b.Hls.play (http://127.0.0.1/player/hls.min.js:3:4251)
    at vjs.Player.techCall (http://127.0.0.1/player/core/video.dev.js:4306:24)
    at vjs.Player.play (http://127.0.0.1/player/core/video.dev.js:4351:8)
    at vjs.MediaTechController.onClick (http://127.0.0.1/player/core/video.dev.js:6709:21)
    at HTMLDivElement.ret (http://127.0.0.1/player/core/video.dev.js:885:15)
    at HTMLObjectElement.data.dispatcher (http://127.0.0.1/player/core/video.dev.js:360:29)

```
but the video can not continue to play

**Comment by writethesky** [comment]
Why is video.dev.js different file with video.js ?

Where there is a document detailing the difference between video.dev.js and video.js file?

**Comment by mmcc** [comment]
It's a common convention in the client-side JS world to provide both a minified version (video.js) and unminified (video.dev.js). 4.x versions of Video.js were mangled pretty aggressively by Closure compiler, which allowed us to make the file size considerably smaller but leads to some issues around exporting methods. We dropped Closure compiler in 5.0 (master).

"Continuing to play" through an error isn't improved behavior, we should try to figure out which plugin is causing the issue. Have you tried to narrow it down at all yet?

**Comment by mmcc** [comment]
Closing this since it appears to be a plugin-specific issue, but we can reopen if necessary.

**Comment by writethesky** [comment]
I seem to find out the reason of the error 

In previous versions 

```
player.on('play', function() {
	alert("---");
	player.on("ended", function(){
		alert(589);
	});
	//player.trigger('adpauseend');
		
});
```
This writing is correct 

But in the current version 

This kind of writing is wrong 

Will not alert 123
