### ISSUE TITLE
Uncaught TypeError: this.c.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by rexDainiel** [videojs/video.js#2483]
I'm trying to play a rtmp stream in my website, but it seem that someplace is not correct so that video.js throw some error: 
```
VIDEOJS: Video.js: currentTime unavailable on Flash playback technology element. TypeError: this.c.vjs_getProperty is not a function
    at ua.(anonymous function) [as seeking] (http://localhost:3000/js/video.js:142:171)
    at t.g.currentTime (http://localhost:3000/js/video.js:140:290)
    at M (http://localhost:3000/js/video.js:68:160)
    at s.currentTime (http://localhost:3000/js/video.js:69:146)
    at t.ub.fa (http://localhost:3000/js/video.js:87:377)
    at e (http://localhost:3000/js/video.js:14:285)
    at HTMLDivElement.e (http://localhost:3000/js/video.js:14:285)
    at HTMLDivElement.t.b.e.ba.e.ba (http://localhost:3000/js/video.js:7:288)
    at Function.t.o (http://localhost:3000/js/video.js:11:175)
    at s.o (http://localhost:3000/js/video.js:37:423)
```

I have no idea where is wrong, so I try to submit this Issue to ask you for any suggestion.

**Comment by mmcc** [comment]
Do you have an example you can show? It looks like you're trying to seek within an RTMP stream, which wouldn't work with something like RTMP.

Closing this, but if you put up an example we can take a look and reopen if we need to.
