### ISSUE TITLE
currentSrc unavailable on Hls playback technology element. TypeError: this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by monte-hayward** [videojs/video.js#2522]
Similarly to #2288 and videojs-contrib-hls#235, this happens when the Flash fallback is in use.
I believe it is unrelated to HLS, since I can get this result with a single MP4.

```
VIDEOJS: Video.js: currentSrc unavailable on Hls playback technology element. TypeError: this.el_.vjs_getProperty is not a function
    at vjs.Flash.currentSrc (http://localhost:8080/142bbf1e4256ea92e8ae.bundle.js:47774:22)
    at vjs.Player.techGet (http://localhost:8080/142bbf1e4256ea92e8ae.bundle.js:44163:32)
    at vjs.Player.currentSrc (http://localhost:8080/142bbf1e4256ea92e8ae.bundle.js:44775:16)
    at videojs.Hls.fillBuffer (http://localhost:8080/142bbf1e4256ea92e8ae.bundle.js:50765:16)
    at videojs.Hls.checkBuffer_ (http://localhost:8080/142bbf1e4256ea92e8ae.bundle.js:50714:9)
    at vjs.bind.ret (http://localhost:8080/142bbf1e4256ea92e8ae.bundle.js:40726:16)
```

**Comment by MichealPAPA** [comment]
The same thing happened to me, and the release of videojs-contrib-hls is 0.17.9, and video.js is 4.12.15.  
Sometimes an exception was thrown at endOfStream in videojs-media-sources.js,
There must be some correlation between the two.

**Comment by gkatsev** [comment]
I think this is either fixed or a Flash issue we can't do anything about (maybe make it better with more try/catches).
Closing this issue due to lack of activity. If it is still a problem and we get more information and a reduced test case, we will happily re-open the issue.
