### ISSUE TITLE
Dynamically change the src property of the video

### ISSUE THREAD

**Issue by NandaG** [videojs/video.js#2564]
Hello,

  I am using videojs to render rtmp video in the application in Angularjs.

here is my Html code.
                   ```<video id="example_video_1"  class="video-js vjs-default-skin width-100p" 
                   controls preload="auto" data-setup=''>
                    <source src=""  id="custPlayer" type='rtmp/mp4'>
                    <p>No Support for HTML 5 video</p>
                  </video> ```
In the controller on the json response i am assigning the src value like

$scope.video =rtmp://ip-address/videochat/agent_2015-08-07_133838_client_2_4001_2_510";
                var agentMp4Vid = document.getElementById('custPlayer');
               $("#agentMp4Vid").attr("src", $scope.video);

I am getting error : VIDEOJS: Error: Error: An invalid exception was thrown.
    at Error (native)
    at s.play (eval at <anonymous> (http://Application/client/lib/jquery-1.11.3.js:339:22), <anonymous>:139:316)
    at N (eval at <anonymous> (http://Application/client/lib/jquery-1.11.3.js:339:22), <anonymous>:68:80)
    at s.play (eval at <anonymous> (http://Application/client/lib/jquery-1.11.3.js:339:22), <anonymous>:68:411)
    at t.rb.u (eval at <anonymous> (http://Application/client/lib/jquery-1.11.3.js:339:22), <anonymous>:109:331)
    at HTMLDivElement.e (eval at <anonymous> (http:/Applicationn/client/lib/jquery-1.11.3.js:339:22), <anonymous>:14:285)
    at HTMLDivElement.t.b.e.ba.e.ba (eval at <anonymous> (http://Applicationn/client/lib/jquery-1.11.3.js:339:22), <anonymous>:7:288)

Please guide me on the same

Thanks

**Comment by mmcc** [comment]
Hi there, you should use the [src method](https://github.com/videojs/video.js/blob/stable/docs/api/vjs.Player.md#src-source-) instead of updating the dom. As a general rule of thumb,once you initialize a player, you should only interact with the video element via the Video.js API.
