### ISSUE TITLE
Node.JS 4.1 Build Failed

### ISSUE THREAD

**Issue by typcn** [videojs/video.js#2643]
```
gyp: /Users/typcn/.node-gyp/4.1.1/common.gypi not found (cwd: /Volumes/M3/projects/live/vjs/node_modules/grunt-sass/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Volumes/M3/projects/live/vjs/node_modules/grunt-sass/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/Volumes/M3/projects/live/vjs/node_modules/grunt-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Volumes/M3/projects/live/vjs/node_modules/grunt-sass/node_modules/node-sass
gyp ERR! node -v v4.1.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed
```

**Comment by gkatsev** [comment]
Sounds like node-sass doesn't have node 4.1.1 compatible binaries.

**Comment by typcn** [comment]
I found solution

The 3.x release of node-sass support node 4.1.1 ( https://github.com/sass/node-sass/releases ).

Grunt-sass 1.0 is using node-sass 3.0 ( https://github.com/sindresorhus/grunt-sass/releases )

So just change grunt-sass version to 1.0 in package.json ( https://github.com/videojs/video.js/blob/master/package.json#L67 )

**Comment by gkatsev** [comment]
Cool. Want to submit a PR with that change?

**Comment by Soviut** [comment]
Please accept the pull request if it's working. I'm experiencing this issue on both Windows and Ubuntu in a Vagrant box I specifically set up hoping to get around the build problems in node 4.1.

**Comment by gkatsev** [comment]
It's been merged. Thanks @typcn.
