### ISSUE TITLE
isCrossOrigin test Fail on IE 11

### ISSUE THREAD

**Issue by Naouak** [videojs/video.js#3100]
When trying to build on windows 10, I get this output with Karma tests:
````
IE 11.0.0 (Windows 10 0.0.0) url isCrossOrigin can identify cross origin urls FAILED
        //google.com from http://google.com is not cross origin
        Expected: true
        Actual: false
           at Anonymous function (/video.js/node_modules/qunitjs/qunit/qunit.js:2145:5)
           at Anonymous function (***/Temp/eaf8d6bff56c5e86c49b7c014c3af2eb.browserify:34838:3 <- ..\unit\utils\test\unit\utils\url.test.js:86:2)
           at runTest (/video.js/node_modules/qunitjs/qunit/qunit.js:903:4)
           at Test.prototype.run (/video.js/node_modules/qunitjs/qunit/qunit.js:888:4)
           at Anonymous function (/video.js/node_modules/qunitjs/qunit/qunit.js:1030:6)
           at process (/video.js/node_modules/qunitjs/qunit/qunit.js:691:4)

.........
IE 11.0.0 (Windows 10 0.0.0): Executed 285 of 285 (1 FAILED) (6.589 secs / 6.506 secs)
````

**Comment by gkatsev** [comment]
Sounds like we should just remove that particular check then. I did try and make sure it worked across all browsers and it passes locally.
What version of IE11 are you using? I wonder if it's related to being Windows 10 as well.
We should try to fix it if possible but otherwise just remove that assertion because it's not worth it otherwise.

**Comment by Naouak** [comment]
Karma launch IE and not Edge (don't really know why).
I got IE 11.63.10586.0 / 11.0.26 (KB3104002).

I'm not sure what the test is use for as it is a security enforced by the browser and the player shouldn't really have to check for it.

**Comment by gkatsev** [comment]
It probably isn't launching edge because we don't have the karma edge launcher [installed](https://github.com/videojs/video.js/blob/084bcf692ced2848973fe8b0c4fad6d745231b4c/package.json#L73-L81). As for the security aspect, this is a test to make sure that the `isCorssOrigin` method is returning the correct results. It isn't testing whether the browser is enforcing cross origin. The way that the check is written, though, makes it hard to test in a completely browser-independent way since it relies on a browser feature to do the check.

**Comment by gkatsev** [comment]
Also, you have a newer version of IE11 than I do, which may or may not be the issue.

**Comment by gkatsev** [comment]
Closing this issue due to lack of activity. If it is still a problem and we get more information and a reduced test case, we will happily re-open the issue.

**Comment by MarcAMo** [comment]
I tried to reproduce this issue, as the test fails for me as well (two different machines with Win10x64 and IE11).
Appearently the problem is, that parseUrl returns {[...], protocol: ""} on IE and {[...], protocol: "https:"} on chrome when calling parseUrl("//www.google.com") from "http://www.google.com".

But I am not sure what causes this.
