### ISSUE TITLE
Mocha testing error USER_AGENT

### ISSUE THREAD

**Issue by gaglage** [videojs/video.js#3500]
Trying to test a project that includes videoJS I got the error below

Test command line:  mocha --compilers js:babel-core/register --recursive ./test/*.js

D:\project\node_modules\video.js\dist\video.js:21329
            var USER_AGENT = _globalWindow2['default'].navigator.userAgent;
                                                                ^

TypeError: Cannot read property 'userAgent' of undefined
    at Object.140.global/document (D:\project\node_modules\video.js\dist\video.js:21329:65)
    at s (D:\project\node_modules\video.js\dist\video.js:32:25)
    at D:\project\node_modules\video.js\dist\video.js:34:28
    at Object.113../big-play-button.js (D:\project\node_modules\video.js\dist\video.js:11145:35)
    at s (D:\project\node_modules\video.js\dist\video.js:32:25)
    at D:\project\node_modules\video.js\dist\video.js:34:28
    at Object.154.../../src/js/utils/merge-options.js (D:\project\node_modules\video.js\dist\video.js:23321:27)
    at s (D:\project\node_modules\video.js\dist\video.js:32:25)
    at e (D:\project\node_modules\video.js\dist\video.js:40:44)
    at D:\project\node_modules\video.js\dist\video.js:42:7
    at a (D:\project\node_modules\video.js\dist\video.js:14:90)
    at Object.<anonymous> (D:\project\node_modules\video.js\dist\video.js:19:3)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\project\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (playerHandler.js:6:32)
    at Module._compile (module.js:541:32)
    at loader (D:\project\node_modules\babel-register\lib\node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\project\node_modules\babel-register\lib\node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (playerHandler.spec.js:5:1)
    at Module._compile (module.js:541:32)
    at loader (D:\project\node_modules\babel-register\lib\node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\project\node_modules\babel-register\lib\node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at D:\project\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\project\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (D:\project\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (D:\project\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
npm ERR! Test failed.  See above for more details.

**Comment by gaglage** [comment]
Problem solved using https://github.com/dmatteo/jsdomify
