### ISSUE TITLE
NPM install errors

### ISSUE THREAD

**Issue by daslicht** [videojs/video.js#3877]
## Description
When I try to install video.js via npm I get the following errors:

## Steps to reproduce

1. ```npm install --save video.js```

### Error output
```
$ npm install --save video.js

> node-zopfli@2.0.2 install /srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/build'
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
make: g++: Command not found
make: *** [Release/obj.target/zopfli/src/zopfli-binding.o] Error 127
make: Leaving directory `/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "/srv/users/shopify/.nvm/versions/node/v7.2.1/bin/node" "/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/lib/binding/node-v51-linux-x64"
gyp ERR! cwd /srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/srv/users/shopify/.nvm/versions/node/v7.2.1/bin/node /srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node --module_name=zopfli --module_path=/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/lib/binding/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.13.0-79-generic
node-pre-gyp ERR! command "/srv/users/shopify/.nvm/versions/node/v7.2.1/bin/node" "/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/srv/users/shopify/.nvm/versions/node/v7.2.1/bin/node /srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node --module_name=zopfli --module_path=/srv/users/shopify/apps/product-videos/public/themes/product-videos/node_modules/node-zopfli/lib/binding/node-v51-linux-x64' (1)
product-video-october-theme@1.0.1 /srv/users/shopify/apps/product-videos/public/themes/product-videos
├── UNMET PEER DEPENDENCY tslint@4.1.1
└─┬ video.js@5.12.6 
  ├─┬ global@4.3.0 
  │ ├─┬ min-document@2.19.0 
  │ │ └── dom-walk@0.1.1 
  │ └── process@0.5.2 
  ├── lodash-compat@3.10.2 
  ├── object.assign@4.0.4 
  ├─┬ safe-json-parse@4.0.0 
  │ └─┬ rust-result@1.0.0 
  │   └── individual@2.0.0 
  ├── tsml@1.0.1 
  ├── videojs-font@2.0.0 
  ├─┬ videojs-ie8@1.1.2 
  │ └── es5-shim@4.5.9 
  ├── videojs-swf@5.1.0 
  ├── videojs-vtt.js@0.12.1 
  └─┬ xhr@2.2.0 
    ├── is-function@1.0.1 
    ├── once@1.1.1 
    └─┬ parse-headers@2.0.1 
      ├── for-each@0.3.2 
      └── trim@0.0.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN codelyzer@2.0.0-beta.3 requires a peer of tslint@~4.0.0 but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 (node_modules/node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
$ 
```

Any idea whats wrong ?

**Comment by JumpLink** [comment]
If I just read your error message, I see 
```
make: g++: Command not found`
```
so if you are using Ubuntu you need to install g++, because this command is not found: `apt install g++`.
If this is not working try to install a collection of build tools with `apt install build-essential`.
You are German, so you could take a look at [ubuntuusers.de](https://wiki.ubuntuusers.de/Programme_kompilieren/).

**Comment by gkatsev** [comment]
It looks like the issue was with node-zopfli failing to build because node-gyp didn't download.
