### ISSUE TITLE
Error when setting textTrackSettings to false

### ISSUE THREAD

**Issue by ookami125** [videojs/video.js#4964]
To put it simply I created a new videojs object with the propery textTrackSettings: false and I added a remote text track. After that I click on the CC button and click on the remote track that was just added then error below pops up.
```
video.js:498 VIDEOJS: ERROR: TypeError: Cannot read property 'getValues' of undefined
    at TextTrackDisplay.updateForTrack (http://vjs.zencdn.net/6.6.3/video.js:12225:52)
    at TextTrackDisplay.updateDisplay (http://vjs.zencdn.net/6.6.3/video.js:12203:12)
    at Player.bound (http://vjs.zencdn.net/6.6.3/video.js:2345:15)
    at HTMLDivElement.bound (http://vjs.zencdn.net/6.6.3/video.js:2345:15)
    at HTMLDivElement.data.dispatcher (http://vjs.zencdn.net/6.6.3/video.js:1971:31)
    at trigger (http://vjs.zencdn.net/6.6.3/video.js:2100:25)
    at Player.trigger$$1 [as trigger] (http://vjs.zencdn.net/6.6.3/video.js:2908:12)
    at Player.(anonymous function) [as handleTechTexttrackchange_] (http://vjs.zencdn.net/6.6.3/video.js:24266:17)
    at Html5.bound (http://vjs.zencdn.net/6.6.3/video.js:2345:15)
    at HTMLVideoElement.bound (http://vjs.zencdn.net/6.6.3/video.js:2345:15)
```
videojs version: 6.6.3
browsers: chrome, firefox
os: windows 10
what platforms (operating systems and devices) are affected?
plugins:
I'm using a custom plugin that I'm developing but the only thing it does is adds remote text tracks. So i believe this in itself doesn't matter. If it turns out it does I'll commit it to github so you can look it over.

**Comment by ldayananda** [comment]
Hmm, seems like this is due to accessing [textTrackSettings without checking if it was included](https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-display.js#L273). Would you be willing to make a PR to fix this?
