### ISSUE TITLE
resizeHandler still triggering events after player disposed

### ISSUE THREAD

**Issue by santialbo** [videojs/video.js#5015]
## Description
I'm getting a somewhat hard to reproduce bug. I'm using Angular 5 in order to create a video component with the videojs/videojs-youtube tech.

I'm instantiating the player on the `ngAfterViewInit` lifecyle method (this is where you would usually do it with other non-angular libraries) and everything is OK.

However when destroying the component, in the `ngOnDestroy` method I call the following methods:

```ts
      this.player.off('timeupdate', this.onTimeUpdate); // unregistering an event that is just logging the progress
      this.player.dispose();
```
What happens is `.dispose()` is throwing the following Exception

```
Error: The YouTube player is not attached to the DOM.
    at Y.g.B (https://s.ytimg.com/yts/jsbin/www-widgetapi-vfllf5xrd/www-widgetapi.js:94:224)
    at X (https://s.ytimg.com/yts/jsbin/www-widgetapi-vfllf5xrd/www-widgetapi.js:86:99)
    at Y.(anonymous function).getCurrentTime.bb.(anonymous function) [as stopVideo] (https://s.ytimg.com/yts/jsbin/www-widgetapi-vfllf5xrd/www-widgetapi.js:104:124)
    at constructor.dispose (http://localhost:6006/static/preview.bundle.js:177702:25)
    at Player.dispose (http://localhost:6006/static/preview.bundle.js:168068:18)
    at VideoComponent.ngOnDestroy (http://localhost:6006/static/preview.bundle.js:148955:25)
```
If I catch it, on Chrome (Firefox is OK) I get the following Exception

```
video.cjs.js:1597 Uncaught TypeError: Cannot read property 'vdata1521052985455' of null
    at hasData (video.cjs.js:1597)
    at trigger (video.cjs.js:2023)
    at Player.trigger$$1 [as trigger] (video.cjs.js:2898)
    at ResizeManager.resizeHandler (video.cjs.js:16750)
    at ResizeObserver.<anonymous> (video.cjs.js:16711)
    at Player.later (video.cjs.js:2362)
    at bound (video.cjs.js:2282)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:496)
```
So it looks like the ResizeManager is triggering a `playerresize` Event.

Do you have any hints or ideas of what could be causing this?

Thanks a lot

**Comment by gkatsev** [comment]
Thanks for the issue. Seems like we potentially aren't disposing of the new ResizeManager properly, for example the debounceHandler_ not being cleared correctly.

**Comment by santialbo** [comment]
Any idea why I could be getting the first Exception?

**Comment by gkatsev** [comment]
Could it be that angular is removing the video element from the DOM before video.js and the youtube tech are done?

**Comment by santialbo** [comment]
I think I can close this since I suspect that it's very likely due to https://github.com/angular/angular/issues/14252

**Comment by gkatsev** [comment]
Ah, that would make sense. a lot of the work that Video.js does regarding events is tied to the DOM element associated with the component, so, if the DOM element is removed, video.js won't be able to remove the event listeners.
We really do need a better error for this issue so that at least it leads you in the right direction.

**Comment by santialbo** [comment]
Yes, usually you expect the documentation of a major framework like Angular to be accurate 😝 
Thanks for your help!

**Comment by gkatsev** [comment]
Hehe, it happens. You're welcome.
