### ISSUE TITLE
Version 7.2.4 still working with requirejs but 7.3.0 not

### ISSUE THREAD

**Issue by b3wii** [videojs/video.js#6272]
Does anyone have an idea? It asks for a global/window.js and global/document.js but when i add them i get this error:

Running "requirejs:compile" (requirejs) task
{ Error: TypeError: Cannot read property 'type' of undefined
    at Function.parse.parseNode (c:\node_modules\requirejs\bin\r.js:25902:25)

    at c:\node_modules\requirejs\bin\r.js:28332:19
    at c:\node_modules\requirejs\bin\r.js:3059:39
    at c:\node_modules\requirejs\bin\r.js:2999:25
    at Function.prim.nextTick (c:\node_modules\requirejs\bin\r.js:28083:9)
    at Object.errback (c:\node_modules\requirejs\bin\r.js:2998:26)
    at Object.callback (c:\node_modules\requirejs\bin\r.js:2984:23)
    at Object.then (c:\node_modules\requirejs\bin\r.js:3038:23)
    at build (c:\node_modules\requirejs\bin\r.js:28289:12)
    at runBuild (c:\node_modules\requirejs\bin\r.js:30302:17)
    at Object.execCb (c:\node_modules\requirejs\bin\r.js:1946:33)
  originalError: TypeError: Cannot read property 'type' of undefined
    at Function.parse.parseNode (c:\node_modules\requirejs\bin\r.js:25902:25)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25193:27)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35)
    at Function.parse.recurse (c:\node_modules\requirejs\bin\r.js:25229:35) }

Thats the requirejs config:

require.config({
    baseUrl: '/',
    paths: {
        'jquery': 'web/vendor/jquery/dist/jquery',
        'videojs': 'web/vendor/videojs/video.min',
    }
});

Videojs is used like this:

define([
'jquery',
'videojs'
], function($, videojs) {
'use strict';

var obj = {
return obj;
});

**Comment by b3wii** [comment]
I got it working with the following code and not using the minified video.js: 

define('global/window', [], function () {
    return window;
});

define('global/document', ['global/window'], function (window) {
    return window.document;
});

**Comment by mafar** [comment]
to fix this, please read my answer https://github.com/videojs/video.js/issues/5680#issuecomment-570120497

I think document should be updated !!!
