### ISSUE TITLE
`npm run start` via WSL ends up with error

### ISSUE THREAD

**Issue by AlexRAV** [videojs/video.js#6388]
## Description
I've cloned video.js repository, to my locale machine and tried to run `npm run start` via WSL but getting the error with following output:

video.js@7.7.4 postbuild:css:cdn /home/alexrav/education/video.js
postcss --verbose --config postcss.config.js -d dist/alt dist/alt/video-js-cdn.css

07 01 2020 18:20:05.178:ERROR [config]: Error in config file!
  Error: Command failed: wslpath -w "/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin"
wslpath: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin: Result not representable

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at getAllPrefixesWsl (/home/alexrav/education/video.js/node_modules/karma-firefox-launcher/index.js:82:23)
    at getFirefoxExeWsl (/home/alexrav/education/video.js/node_modules/karma-firefox-launcher/index.js:113:22)
    at Object.<anonymous> (/home/alexrav/education/video.js/node_modules/karma-firefox-launcher/index.js:254:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/alexrav/education/video.js/node_modules/videojs-generate-karma-config/index.js:10:23
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/alexrav/education/video.js/node_modules/videojs-generate-karma-config/index.js:8:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/alexrav/education/video.js/test/karma.conf.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video.js@7.7.4 karma-server: `karma start test/karma.conf.js --singleRun=false --auto-watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video.js@7.7.4 karma-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexrav/.npm/_logs/2020-01-07T11_20_06_603Z-debug.log
ERROR: "karma-server" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video.js@7.7.4 start: `npm-run-all -p watch karma-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video.js@7.7.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexrav/.npm/_logs/2020-01-07T11_20_06_694Z-debug.log
`

## Steps to reproduce
1. Install WSL;
2. Clone repo;
3. Run `npm run start` via WSL;

I've tried to reproduce this issue on a pure karma project, but it doesn't reproduce.
Even if I change karma-server command to `karma start` (without additional parameters), I still getting error.
Also, I've tried to run video.js with latest karma version(4.4.1), but nothing had changed.

**Comment by gkatsev** [comment]
Unfortunately, because we develop on macs, we've mostly focused there. We're tried to keep things fairly agnostic, but it's possible tooling we're using don't work on WSL, karma for example may not be able to be run via WSL.
