### ISSUE TITLE
tests are looking for .dnx/bin in wrong folder on WSL 2

### ISSUE THREAD

**Issue by AwokeKnowing** [videojs/video.js#6829]
## Description

I have no idea why the test is looking for wslpath -w "/mnt/c/Users/james.m_2/.dnx/bin"

there is some wrong logic in tests because the actual home is ~/  ie /home/james  .  that path above is the Windows home but is not relevant, it's just a mount of the windows filesystem into linux, to access windows files

after following install, during npm test, everything builds but near end I get:

wslpath: /mnt/c/Users/james.m_2/.dnx/bin: No such file or directory
02 09 2020 16:07:56.662:ERROR [config]: Error in config file!
  Error: Command failed: wslpath -w "/mnt/c/Users/james.m_2/.dnx/bin"
wslpath: /mnt/c/Users/james.m_2/.dnx/bin: No such file or directory

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at getAllPrefixesWsl (/home/james/gits/awokeknowing/video.js/node_modules/karma-firefox-launcher/index.js:82:23)
    at getFirefoxExeWsl (/home/james/gits/awokeknowing/video.js/node_modules/karma-firefox-launcher/index.js:113:22)
    at Object.<anonymous> (/home/james/gits/awokeknowing/video.js/node_modules/karma-firefox-launcher/index.js:254:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/james/gits/awokeknowing/video.js/node_modules/videojs-generate-karma-config/index.js:10:23
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/james/gits/awokeknowing/video.js/node_modules/videojs-generate-karma-config/index.js:8:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
set up wsl2 ubuntu 20.04
install nodejs and npm
clone the repo
run npm install 
run npm test

### Expected
error

### Actual
see above

### Error output
see above

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.9.3
#### browsers
what browser are affected?
#### OSes
WSL2 windows 10 ubuntu 20.04
### plugins
no

**Comment by gkatsev** [comment]
This is likely an issue with karma or more specifically the firefox launcher. There was a fix that may help from january. What version of karma-firefox-launcher is being used for you? Can you run `npm ls karma-firefox-launcher` and report back? If it isn't 1.3.0, can you try removing the `package-lock.json` file reinstalling and see whether that works?
