### ISSUE TITLE
The Video JS home page doesn't work in IE11

### ISSUE THREAD

**Issue by lev312** [videojs/video.js#7149]
## Description
We have several problems related to IE 11.  Does IE11 officially supported by VideoJS?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open https://videojs.com/ in Internet Explorer 11 (IE11)

### Expected
User can see the video.

### Actual
Video can not be played.

### Error output
```
SCRIPT5: Access is denied.

zdconsent.js (2,364)
SCRIPT1002: Syntax error
4-ec9abec68df92920b7ad.js (1,3752)
SCRIPT1002: Syntax error
4-ec9abec68df92920b7ad.js (1,3752)
SCRIPT1010: Expected identifier
c4ef0f2457c5f4a8581020d785c6472d9c9f6a94.d73d63e7384b25c1bac6.js (1,8574)
SCRIPT1002: Syntax error
c6e813a11c04a409939b4de653df818c642f514d.3380a67fcfc341a24338.js (1,6300)
Error: Missing resources for /
   {
      [functions]: ,
      __proto__: { },
      description: "Missing resources for /",
      message: "Missing resources for /",
      name: "Error",
      stack: "Error: Missing resources for /
   at n.render (https://videojs.com/app-473a7657e1179285ee4a.js:1:968222)
   at Pa (https://videojs.com/app-473a7657e1179285ee4a.js:1:734079)
   at Ca (https://videojs.com/app-473a7657e1179285ee4a.js:1:733929)
   at La (https://videojs.com/app-473a7657e1179285ee4a.js:1:737737)
   at Go (https://videojs.com/app-473a7657e1179285ee4a.js:1:761808)
   at Xo (https://videojs.com/app-473a7657e1179285ee4a.js:1:762195)
   at Is (https://videojs.com/app-473a7657e1179285ee4a.js:1:769085)
   at Cs (https://videojs.com/app-473a7657e1179285ee4a.js:1:768465)
   at As (https://videojs.com/app-473a7657e1179285ee4a.js:1:767486)
   at Zo (https://videojs.com/app-473a7657e1179285ee4a.js:1:766360)"
   }

Error: Missing resources for /
   {
      [functions]: ,
      __proto__: { },
      description: "Missing resources for /",
      message: "Missing resources for /",
      name: "Error",
      stack: "Error: Missing resources for /
   at n.render (https://videojs.com/app-473a7657e1179285ee4a.js:1:968222)
   at Pa (https://videojs.com/app-473a7657e1179285ee4a.js:1:734079)
   at Ca (https://videojs.com/app-473a7657e1179285ee4a.js:1:733929)
   at La (https://videojs.com/app-473a7657e1179285ee4a.js:1:737737)
   at Go (https://videojs.com/app-473a7657e1179285ee4a.js:1:761808)
   at Xo (https://videojs.com/app-473a7657e1179285ee4a.js:1:762195)
   at Is (https://videojs.com/app-473a7657e1179285ee4a.js:1:769085)
   at Cs (https://videojs.com/app-473a7657e1179285ee4a.js:1:768465)
   at As (https://videojs.com/app-473a7657e1179285ee4a.js:1:767486)
   at Zo (https://videojs.com/app-473a7657e1179285ee4a.js:1:766360)"
   }

SCRIPT5022: Missing resources for /
app-473a7657e1179285ee4a.js (1,768646)

```

## Additional Information
-
#### videojs
The one you have on your website
#### browsers
Internet Explorer 11 ( 19042.867)
#### OSes
Windows 10, any PC (laptops, desktops,...)
### plugins
-

![VideoJs](https://user-images.githubusercontent.com/43747525/112461332-7bea4d00-8d68-11eb-871e-1891276ede09.png)

**Comment by gkatsev** [comment]
Sounds like it never worked with the new re-design. Thankfully, this it was relatively easy to fix https://github.com/videojs/videojs.com/pull/127
However, we're probably not going to be supporting IE11 much longer.

**Comment by gkatsev** [comment]
Merged the fix, it should deploy in a minute.

**Comment by lev312** [comment]
@gkatsev thank you for the answer!
