### ISSUE TITLE
Npm build and npm test fail with TypeError and or multiple errors

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#7216]
## Description
Both `npm run build` and `npm run test` fail with a `TypeError` or multiple other errors in my local vanilla clone of the video.js repository with no local changes. `npm run start` works as expected.

## Steps to reproduce
I have reproduced this both in Ubuntu in WSL on Windows and natively on Windows
1. In WSL Ubuntu open a Linux Bash Shell.
2. In the shell navigate to the directory where you want to clone video.js.
3. Type `$ git clone https://github.com/videojs/video.js.git`
4. Type `npm install` and wait for it to finish.
5. Type `npm test` or `npm build`

### Expected
According to the [Contributing Guide](https://github.com/videojs/video.js/blob/main/CONTRIBUTING.md#running-tests) `npm test` and `npm build` should complete without errors.

### Actual
Both `npm test` and `npm build` fail with errors.

### Error output
This is a copy and paste of typical error output from `npm build`, `npm test` appears to give identical output.
```
$ npm run build
 run build

> video.js@7.12.1 build
> npm-run-all build-dev minify copy zip


> video.js@7.12.1 build-dev
> npm-run-all clean lint-errors build:js build:css build:lang build:test


> video.js@7.12.1 clean
> shx rm -rf ./dist ./test/dist ./docs/api ./lang/zh-Han*.json

(node:3248) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3248) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:3248) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

> video.js@7.12.1 postclean
> shx mkdir -p ./dist/lang ./test/dist

(node:3256) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3256) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:3256) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

> video.js@7.12.1 lint-errors
> vjsstandard --errors



> video.js@7.12.1 build:js
> rollup -c

[!] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
    at Object.writeFileSync (fs.js:1460:5)
    at progress (/mnt/f/Server/packages/video.js/node_modules/rollup-plugin-progress/dist/rollup-plugin-progress.js:25:8)
    at progress (/mnt/f/Server/packages/video.js/rollup.config.js:72:10)
    at rollup_config (/mnt/f/Server/packages/video.js/rollup.config.js:134:36)
    at /mnt/f/Server/packages/video.js/node_modules/rollup/dist/bin/rollup:1869:24

ERROR: "build:js" exited with 1.
ERROR: "build-dev" exited with 1.
```

## Additional Information
When executing `npm start` both `http://localhost:9999/test` and `http://localhost:9999/sandbox/index.html` work as expected.

#### Videojs
Version 7.12.1
#### Browsers
Chrome latest
#### OSes
Windows 10, WSL 1 running Ubuntu 20.04.1 LTS
#### Node
Version 14.16.1
#### NPM
Version 7.11.2
### Plugins
None, this is a vanilla clone of the main branch of video.js

**Comment by edwinbradford** [comment]
I finally resolved this after a couple of days trying to figure it out. Along with the `TypeError` reported in this issue I was also intermediately getting around 5000 `vjsstandard --error` errors referring mostly to incorrectly formatted quotation marks and indentations in language files.

The language files were in a folder `temp` inside the build directory and not on GitHub. I deleted `build/temp` , ran  `npm run build` as normal and everything worked as expected.

I have no idea what caused building to fail initially as I followed the guidelines to the letter but there seems to be an issue here that at least in my development environment once the build failed once it will no longer work unless you delete the temp directory.

**Comment by edwinbradford** [comment]
Further testing indicates if you follow the contributing guidelines---at least on Windows---the current version 7.12.1 will neither build nor test and will instead produce the error reported in this ticket. This issue is reproducible on my local machine. To successfully build you have to also run `npm update` after running `npm install`. If you run `npm audit` I believe it will also fail to build but I haven't verified that.

Since there is no reference to `npm update` or `npm audit` in the guidelines and one appears to be required but the other not it seems like there is an issue here that needs fixing.

**Comment by brandonocasey** [comment]
We have yet to update this repo to node 14, and a lot of our tooling needs to be updated to support that version of node. We also don't have many people that work on Windows and tooling support hasn't really gotten a proper test. Likely there are issues you are running into related to that. Would you mind trying node 10 for now? I know that's not ideal but we are working towards moving everything to node 14 right now.

**Comment by gkatsev** [comment]
node 12 should work as well.

**Comment by gkatsev** [comment]
I just merged an update that should fix things on node 14.

**Comment by edwinbradford** [comment]
I can verify your update works on (WSL) Ubuntu 20.04. I deleted `node_modules`, verified I was using Node 14.x LTS, pulled your changes and ran `npm install` but not `npm update`. The result was `npm build` `npm test` and `npm start` all worked perfectly.

**Comment by gkatsev** [comment]
Awesome, thanks for verifying!
