### ISSUE TITLE
Getting Content Security Policy Error when deployed on CDN.

### ISSUE THREAD

**Issue by bAmrish** [videojs/video.js#7422]
## Description
I am trying to integrate video.js player in my angular application. While I am able to integrate it successfully and it works fine locally (with localhost), I am getting a `Content Security Policy` error, when deployed on CDN (AWS CloudFront backed by S3).

I have added the security policy show below:
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ITeaserApp</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="assets/favicon.svg">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta http-equiv="Content-Security-Policy" content="default-src http: https: data: blob: 'self' 'unsafe-eval' 'unsafe-inline'; worker-src http: https: data: blob: 'self' 'unsafe-eval' 'unsafe-inline';">
</head>
<body>
  <my-app-root></my-app-root>
</body>
</html>


```
## Steps to reproduce
- See description above ---

### Expected
Expected video component to play without error

### Actual
Receiving `Content Security Policy`error show below.

### Error output

```
video.es.js:32051 Refused to create a worker from 'blob:https:/mysubdomain.mycompany.com/ff064232-41e8-4c21-82fe-4b523e4eeae1' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'default-src' is used as a fallback.

(anonymous) @ video.es.js:32051
MasterPlaylistController @ video.es.js:50112
src @ video.es.js:53476
... (lines turncated)
core.js:6210 ERROR DOMException: Failed to construct 'Worker': Access to the script at 'blob:https:/mysubdomain.mycompany.com/ff064232-41e8-4c21-82fe-4b523e4eeae1' is denied by the document's Content Security Policy.
    at new <anonymous> (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:39448:40)
    at new MasterPlaylistController (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:57509:24)
    at VhsHandler.src (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:60873:38)
    at Object.handleSource (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:61403:14)
    at Html5._Tech.setSource (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:17126:30)
    at new Html5 (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:27067:13)
    at Player.loadTech_ (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:30212:18)
    at Player.src_ (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:32652:12)
    at https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:32557:25
    at setSourceHelper (https:/mysubdomain.mycompany.com/modules-presentation-presentation-module.js:17492:5)

```
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.14.3
#### browsers
Firefox and Chrome
#### OSes
MacOS Big Sur and Windows 10
### plugins
No plugins installed

**Comment by bAmrish** [comment]
Closing this issue as this is now resolved. 
CSP set by CDN was overriding CSP I had in `index.html`, causing the issue. Changing the CDN configuration fixed the issue.

https://stackoverflow.com/questions/69164707/content-security-policy-not-working-as-expected
