### ISSUE TITLE
Cannot perform Construct on a detached ArrayBuffer

### ISSUE THREAD

**Issue by wg-daniel** [videojs/video.js#7672]
## Description
We are encountering some errors that we cannot place (or reproduce for that matter). Not sure if it's a bug or even an end-user problem at all. :shrug: 
Main question is, if anyone can place what is happening here and has an idea of what the impact can be.

## Steps to reproduce
Unkown

### Error output
```
TypeError: Cannot perform Construct on a detached ArrayBuffer
  at new Uint8Array(<anonymous>)
  at apply(./node_modules/video.js/dist/video.cjs.js:41390:25)
  at Worker.i(./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.3.31
#### browsers
Chromium-based browsers
(Chrome, Chrome mobile, Edge, Samsung Internet)
#### OSes
Android, Windows, Mac OSx
### plugins
None

**Comment by misteroneill** [comment]
I see `at Worker.i` in there - does that mean this is attempting to run in a Web Worker? That class name doesn't appear to come from Sentry, but it does come from Web Workers.

If so, Media Source Extensions does not currently work in Web Workers. There appears to be ongoing discussion in the W3C on if/how to enable this.

**Comment by kylekirkby** [comment]
We've also just had this error with Sentry. 

```
TypeError: Cannot perform Construct on a detached ArrayBuffer
  at new Uint8Array(<anonymous>)
  at apply(./node_modules/@videojs/http-streaming/dist/videojs-http-streaming.es.js:13161:25)
  at Worker.i(./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

**Comment by wg-daniel** [comment]
@kylekirkby Are you using ID3 tags as well (that you are aware of?)

Sorry for cross-tagging you here, @mister-ben. I saw that you mentioned ID3 que data as a fix for a new major version.
As it seems quite hard to replicate the issue, can you perhaps give an idea of what actual impact there is in these situations?

**Comment by kylekirkby** [comment]
@wg-daniel we are processing our videos with AWS MediaConvert utilising some of the defaults that amplify-video has given us for our MediaConvert templates. I've just done a search in the repo and found this config which suggests we are using `Id3` tags:

```
				"OutputGroupSettings": {
					"Type": "HLS_GROUP_SETTINGS",
					"HlsGroupSettings": {
						"ManifestDurationFormat": "INTEGER",
						"SegmentLength": 10,
						"TimedMetadataId3Period": 10,
						"CaptionLanguageSetting": "OMIT",
						"TimedMetadataId3Frame": "PRIV",
						"CodecSpecification": "RFC_4281",
						"OutputSelection": "MANIFESTS_AND_SEGMENTS",
						"ProgramDateTimePeriod": 600,
						"MinSegmentLength": 0,
						"MinFinalSegmentLength": 0,
						"DirectoryStructure": "SINGLE_DIRECTORY",
						"ProgramDateTime": "EXCLUDE",
						"SegmentControl": "SEGMENTED_FILES",
						"ManifestCompression": "NONE",
						"ClientCache": "ENABLED",
						"StreamInfResolution": "INCLUDE"
					}
				}
```

https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs-id.html

**Comment by mister-ben** [comment]
My comment about ID3 would be a red herring here. It's about doing presenting them more like Safari's native tracks, so you wouldn't have to convert from the Uint8Array that's returned at that point. A convenience when reading the cues from the texttrack, a good step removed from whatever is happening here.

**Comment by misteroneill** [comment]
We can keep this open for the time being, but I believe it may be a VHS issue.

@wg-daniel Do you have any idea of the impact? In other words, is this happening to a lot of users or just some?

**Comment by phloxic** [comment]
May be related, I just ran into 'Uncaught TypeError: attempting to access detached ArrayBuffer' after upgrading to 7.19.0 (maybe I did not notice it before).
No id3 tags, but hls subtitles, Firefox MacOS - so, yes, possibly VHS.
Can't reproduce it so far, sorry.

**Comment by misteroneill** [comment]
@wg-daniel Yeah, I think that's best. If you don't mind creating the issue [here](https://github.com/videojs/http-streaming/issues), that would be a big help!

**Comment by schw4rzlicht** [comment]
I have seen this in Sentry today as well, impacting one user so far.

Windows 10, Chrome 100.0.4896
