### ISSUE TITLE
VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'parts' | 'videoTimingInfo' | 'audioTimingInfo' | 'start' | 'end')

### ISSUE THREAD

**Issue by Aigor79** [videojs/video.js#7718]
## Description
When I play a HLS video, within a corporate network, sometimes the player stops with these errors:

```
TypeError: Cannot read properties of undefined (reading 'parts')
..
Uncaught TypeError: Cannot read properties of undefined (reading 'videoTimimngInfo')
..
Uncaught TypeError: Cannot read properties of undefined (reading 'start')
..
Uncaught TypeError: Cannot read properties of undefined (reading 'audioTimingInfo')
..
Uncaught TypeError: Cannot read properties of undefined (reading 'end')
...
TypeError: Cannot read properties of undefined (reading 'dateTimeObject')
...
TypeError: Cannot read properties of undefined (reading 'uri')

```
These errors are not handled by the player.on('error') event

## Steps to reproduce
It's difficult to reproduce, however I suppose it's enough to force to undefined some attributes of the object _segmentinfo_ inside _generateSegments_.

### Expected
When a segment arrives with wrong information the player should ignore it and continue viewing the video.
In my case it was enough to catch errors in some functions:

- updateMediaSecondsLoaded_
- updateMediaSecondsLoaded_
- handleSegmentTimingInfo_
- calculateSegmentTimeMapping_
- saveSegmentTimingInfo
- segmentInfoString
- addSegmentMetadataCue_
- handleAppendsDone_

I simply added within functions
```
try {
     ....
 } catch (e) {
      videojs.log.warn(e);
}
```
and the player has never stopped

### Actual
When a wrong segment comes the player blocks the view and you have to restart it

### Error output
(line number does not match because of try catches added, however it is version 7.18.1 of videojs)
```
TypeError: Cannot read properties of undefined (reading 'start')
    at SyncController.calculateSegmentTimeMapping_ (video.min.js:60623:30)
    at SyncController.saveSegmentTimingInfo (video.min.js:60526:59)
    at SegmentLoader.handleAppendsDone_ (video.min.js:58397:42)
    at SegmentLoader.checkAppendsDone_ (video.min.js:58269:22)
    at Object.action (video.min.js:58775:17)
    at shiftQueue (video.min.js:58693:20)
    at SourceBuffer.<anonymous> (video.min.js:58912:13)
```

```
TypeError: Cannot read properties of undefined (reading 'dateTimeObject')
    at SyncController.saveSegmentTimingInfo (video.min.js:60541:40)
    at SegmentLoader.handleAppendsDone_ (video.min.js:58397:42)
    at SegmentLoader.checkAppendsDone_ (video.min.js:58269:22)
    at Object.action (video.min.js:58775:17)
    at shiftQueue (video.min.js:58693:20)
    at SourceBuffer.<anonymous> (video.min.js:58912:13)
```

```
TypeError: Cannot read properties of undefined (reading 'uri')
    at segmentInfoString (video.min.js:55579:44)
    at SegmentLoader.handleAppendsDone_ (video.min.js:58429:44)
    at SegmentLoader.checkAppendsDone_ (video.min.js:58269:22)
    at Object.action (video.min.js:58775:17)
    at shiftQueue (video.min.js:58693:20)
    at SourceBuffer.<anonymous> (video.min.js:58912:13)
```

```
TypeError: Cannot read properties of undefined (reading 'end')
    at SegmentLoader.handleAppendsDone_ (video.min.js:58459:47)
    at SegmentLoader.checkAppendsDone_ (video.min.js:58269:22)
    at Object.action (video.min.js:58775:17)
    at shiftQueue (video.min.js:58693:20)
    at SourceBuffer.<anonymous> (video.min.js:58912:13)
```

#### videojs
7.18.1
#### browsers
Edge Chrome Firefox
#### OSes
Windows MacOs
### plugins
no

**Comment by misteroneill** [comment]
Thanks for the detailed report!

The team is currently operating at lower capacity, so it may be a while before we get to this one. It seems like something we should investigate, though.

**Comment by tzarebczan** [comment]
We're also seeing this when switching betweeen quality settings using http-streaming.  
![image](https://user-images.githubusercontent.com/8120721/164077541-b725903d-196c-424c-a21a-42e425837533.png)

Refreshing fixes it, and able to switch normally.

**Comment by tzarebczan** [comment]
Is this potentially fixed here for http-streaming? https://github.com/videojs/http-streaming/releases/tag/v2.14.2 

Possible to get a release with that bump?

**Comment by gkatsev** [comment]
Video.js 7.19.2 just released with that VHS version. Please try it out.

**Comment by tzarebczan** [comment]
Great, i actually overwrote it on our site, launched earlier today. Haven't seen it creep up yet, thank you!
