### ISSUE TITLE
TypeError: Cannot read property 'currentTime' of null

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/video.js#7730]
## Description

We are catching the errors/exceptions in Sentry. We often get these exceptions

- TypeError: Cannot read property 'currentTime' of null

```
TypeError: Cannot read properties of null (reading 'paused')
  at method(../node_modules/video.js/dist/video.es.js:21454:17)
  at get(../node_modules/video.js/dist/video.es.js:9871:66)
  at techGet_(../node_modules/video.js/dist/video.es.js:23999:14)
  at paused(../node_modules/video.js/dist/video.es.js:24162:17)
  at apply(../node_modules/videojs-landscape-fullscreen/dist/videojs-landscape-fullscreen.es.js:69:18)
  at r(../../src/helpers.ts:87:17)
```

- TypeError: Cannot read properties of null (reading 'paused')

```
TypeError: Cannot read properties of null (reading 'paused')
  at method(../node_modules/video.js/dist/video.es.js:21454:17)
  at get(../node_modules/video.js/dist/video.es.js:9871:66)
  at techGet_(../node_modules/video.js/dist/video.es.js:23999:14)
  at paused(../node_modules/video.js/dist/video.es.js:24162:17)
  at apply(../node_modules/videojs-landscape-fullscreen/dist/videojs-landscape-fullscreen.es.js:69:18)
  at r(../../src/helpers.ts:87:17)
```

## Steps to reproduce
Not sure about the steps to reproduce, I guess it's happening because the player is being accessed after it's unmounted. 
I am sure we are disposing the player using `this.videoPlayer.dispose()` in `componentWillUnmount` of React

### Expected
These issues should not be reported

### Actual
These issues are reported

### Error output
Not getting any error in the UI, but these are not thrown in the console

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs 7.14.3
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### Chrome, Firefox
what platforms (operating systems and devices) are affected?
### Windows 10, Andriod 10
are any videojs plugins being used on the page? If so, please list them below.

- "videojs-contrib-dash": "2.11.0"
- "videojs-contrib-quality-levels": "2.1.0"
- "videojs-hotkeys": "0.2.27"
- "videojs-landscape-fullscreen": "1.0.3"
- "videojs-markers-plugin": "1.0.2"
- "videojs-seek-buttons": "1.6.0"
- "@videojs/http-streaming": "1.12.0"
- "videojs-http-source-selector": "1.1.10"

These are not causing any UI issues or crashes, but I am curious why these are happening and if there is something we can do to get rid of these.

**Comment by gkatsev** [comment]
Based on the stack trace snippet, it seems like the issue comes from videojs-landscape-fullscreen. There's likely some event handler that sticks around and isn't getting removed on dispose.

Looking at the code, it seems like they're adding an `orientationchange` event handler but then aren't doing player null checks or removing the handler when the player is disposed: https://github.com/prateekrastogi/videojs-landscape-fullscreen/blob/master/src/plugin.js#L80

**Comment by KVPasupuleti** [comment]
Yeah, got it. Will try raising a PR to videojs-landscape-fullscreen and if the folks there won't respond, will try to handle it in my code.

And what about the `currentTime` exception?

**Comment by gkatsev** [comment]
Looks like the source updated in VHS still updated?
`  at apply(../node_modules/video.js/dist/video.es.js:46525:9)` corresponds to
https://github.com/videojs/http-streaming/blob/80138302483c3e0a9cdfab6d878d24d848f4f8c8/src/source-updater.js#L312

What does your helpers.ts line 87 do?

**Comment by KVPasupuleti** [comment]
I have raised a [PR](https://github.com/prateekrastogi/videojs-landscape-fullscreen/pull/29) for videojs-landscape-fullscreen.

I don't think this is funny, but what is he actually saying?

It's supposed to be nested and I feel that's irrelevant for the issue happened.

And, it seems it's the `TypeError` that's misleading the context there.

**Comment by KVPasupuleti** [comment]
> Looks like the source updated in VHS still updated? ` at apply(../node_modules/video.js/dist/video.es.js:46525:9)` corresponds to https://github.com/videojs/http-streaming/blob/80138302483c3e0a9cdfab6d878d24d848f4f8c8/src/source-updater.js#L312
> 
> What does your helpers.ts line 87 do?

And regarding this, I think `helpers.ts` could probably be supplied by create-react-app with typescript under the hood. 

Not sure what it's actually doing, but I think it's just a wrapper.

**Comment by gkatsev** [comment]
Not sure what the responses in videojs-landscape-fullscreen are about.
