### ISSUE TITLE
video.js @7.19.2 报错

### ISSUE THREAD

**Issue by woaidaim** [videojs/video.js#7829]
### Description

安装依赖后，按照文档进行初始化，但是只要引入 import videojs from "video.js"; ，会控台报错，导致页面无法进入

### Steps to reproduce

1. 安装依赖后，只要引入 import videojs from "video.js"; 就会报错
2.
3.

### Errors

TypeError: Cannot read properties of undefined (reading 'BigInt')
    at eval (byte-helpers.js?de66:77:1)
    at Module../node_modules/@videojs/vhs-utils/es/byte-helpers.js (8.js:88:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at Module.eval (video.es.js?f0e2:1:1)
    at eval (video.es.js:55209:30)
    at Module../node_modules/video.js/dist/video.es.js (8.js:2074:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (videojs.vue?f367:15:1)

### What version of Video.js are you using?

@7.19.2

### What browser(s) including version(s) does this occur with?

谷歌(100.0.4896.127（正式版本） （64 位）)

### What OS(es) and version(s) does this occur with?

window10

**Comment by misteroneill** [comment]
In the future, reporting issues in English would be helpful as it is spoken by core collaborators to Video.js.

From Google, translation is:

> After installing the dependencies, initialize them according to the documentation, but as long as `import videojs from "video.js";` is introduced, an error will be reported in the console, resulting in the inability to enter the page

It sounds like there is a problem with your browser environment like another library changing globals. `BigInt` should be supported and [`byte-helpers.js` falls back to `Number`](https://github.com/videojs/vhs-utils/blob/main/src/byte-helpers.js#L74).

**Comment by Kirshach** [comment]
I'm experiencing exactly the same issue in a Next.js 10 SSR application, where during initial loading of a page I navigate to, loading fails with exactly the same error and the call stack, but if I then refresh the page, everything works fine.

> It sounds like there is a problem with your browser environment like another library changing globals. BigInt should be supported and [byte-helpers.js falls back to Number](https://github.com/videojs/vhs-utils/blob/main/src/byte-helpers.js#L74).

The problem is not with BigInt, rather it seems to be with how webpack handles `global` package - `@videojs/vhs-utils/es/byte-helpers.js` imports `window` from `globals/window`, and somehow that `window` is undefined on initial load.
If it says anything, `TypeError: Cannot read properties of undefined (reading 'BigInt')` is the error in Chrome, whereas Firefox throws a different one: `TypeError: global_window__WEBPACK_IMPORTED_MODULE_0___default.a is undefined`

**Comment by Christopher-Hsieh** [comment]
I am experiencing this issue as well. It's consistently reproducible, but only if I'm a new user, and only on the first time a page is initially loaded.

I also tried to dynamic load the import and wrapped it in a useEffect in order ensure window was defined. An error is still consistently thrown directly related to BigInt.

**Comment by Kirshach** [comment]
After some research I can add that somehow version 7.0.5 doesn't cause that error to happen, but every other version starting with 7.1.0 does, though looking at change logs and diffs for the latter I can't imagine what may cause it

**Comment by damjan25** [comment]
can confirm that this also happens with 7.3.51 and unfortunately for me also with v7.0.5

**Comment by origin3366** [comment]
vue@2.6.14 videoJs@8.3.0 chrome@113.0 
Still happening TypeError: Cannot read properties of undefined (reading 'BigInt')

**Comment by xiaowangge666** [comment]
This error is caused by a conflict between the project's other dependencies and viedojs.You need to spend some time on your own to figure out which dependencies you're in conflict with

**Comment by giserman001** [comment]
I am experiencing this issue as well. It's consistently reproducible,

**Comment by peacepostman** [comment]
Hello ! Same issue for me too, It seems that the page where we are having issues are the pages where an instance of JWplayer is also running.
