### ISSUE TITLE
(CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists

### ISSUE THREAD

**Issue by DetectiveBox** [videojs/video.js#7886]
### Description

when i used videojs to play m3u8, there are some errors. It notes (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists.

### Steps to reproduce

Here is the code
getVideo(item.videoUrl);
  const getVideo = (url: string) => {
    const div: any = document.getElementById('videoDiv');
    div.innerHTML = '';
    div.innerHTML = `<video id="videoPlayer" class="video-js" style="width: 300px; height: 180px;"></video>`;
    const options = {
      autoplay: true, 
      controls: true,
      // errorDisplay: false,
      // muted: true,
      sources: [
        {
          src: url,
          type: 'application/x-mpegURL', 
        },
      ],
    };
    videojs(`videoPlayer`, options, function onPlayerReady() {});
  };

### Errors

video.es.js:42728 Uncaught TypeError: Cannot read properties of null (reading 'aborted')
    at MockXMLHttpRequest.<anonymous> (video.es.js:42728:17)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8472:25)
    at XMLHttpRequest.handle2 (mock.js:8304:19)
(anonymous) @ video.es.js:42728
dispatchEvent @ mock.js:8472
handle2 @ mock.js:8304
XMLHttpRequest.send (async)
send @ mock.js:8363
_createXHR @ index.js:274
createXHR @ index.js:91
XhrFunction @ video.es.js:31145
mediaSegmentRequest2 @ video.es.js:42899
updateTransmuxerAndRequestSegment_ @ video.es.js:46484
loadSegment_ @ video.es.js:46437
fillBuffer_ @ video.es.js:45391
monitorBufferTick_ @ video.es.js:45348
setTimeout (async)
monitorBuffer_ @ video.es.js:45336
load @ video.es.js:44969
load @ video.es.js:51865
setupFirstPlay @ video.es.js:52008
(anonymous) @ video.es.js:51457
data.dispatcher @ video.es.js:2311
trigger @ video.es.js:2447
EventTarget$2.trigger @ video.es.js:2850
setupInitialPlaylist @ video.es.js:31077
(anonymous) @ video.es.js:31014
callbackWrapper2 @ video.es.js:31121
(anonymous) @ video.es.js:31146
cbOnce @ index.js:104
loadFunc @ index.js:178
dispatchEvent @ mock.js:8476
handle2 @ mock.js:8304
load (async)
open @ mock.js:8315
_createXHR @ index.js:232
createXHR @ index.js:91
XhrFunction @ video.es.js:31145
start2 @ video.es.js:30979
load @ video.es.js:30911
MasterPlaylistController2 @ video.es.js:51226
src @ video.es.js:54538
handleSource @ video.es.js:55121
_Tech.setSource @ video.es.js:9920
Html52 @ video.es.js:19980
loadTech_ @ video.es.js:23207
src_ @ video.es.js:25647
(anonymous) @ video.es.js:25552
setSourceHelper @ video.es.js:10286
setSourceHelper @ video.es.js:10288
(anonymous) @ video.es.js:10026
(anonymous) @ video.es.js:5166
setTimeout (async)
setTimeout2 @ video.es.js:5161
setSource @ video.es.js:10025
handleSrc_ @ video.es.js:25542
src @ video.es.js:25618
MediaLoader2 @ video.es.js:10511
addChild @ video.es.js:4249
handleAdd2 @ video.es.js:4381
initChildren @ video.es.js:4430
Player2 @ video.es.js:22520
videojs @ video.es.js:28339
getVideo @ Event.vue:179
handlePlayAnEventVideo @ Event.vue:156
onClick @ Event.vue:26
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:366
video.es.js:228 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. MediaError {code: 3, message: 'Playback cannot continue. No available working or supported playlists.'}

### What version of Video.js are you using?

7.20.2

### What browser(s) including version(s) does this occur with?

chrome latest

### What OS(es) and version(s) does this occur with?

windows 10

**Comment by gkatsev** [comment]
Can you provide the stream that you're playing when you experience this issue? Unfortunately, we can't help without one.

**Comment by DetectiveBox** [comment]
> Can you provide the stream that you're playing when you experience this issue? Unfortunately, we can't help without one.

Hi, thank you for your attention. This is my m3u8 url: https://api-stage.addx.live/video/download/m3u8/011911661222475v2i9vwCX2XF9pe.m3u8?token=eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjExOTEsInRyYWNlSWQiOiIwMTE5MTE2NjEyMjI0NzV2Mmk5dndDWDJYRjlwZSIsImV4cCI6MTY2MTQ4NTQ2OX0.1yxx1g5oltb6nOMOMf76OeniTeJURnePtrv93hPf2xaBcnQovzegnk0cP3FPwl6e-OB5VJ5Z58cusK-53LnICQ

**Comment by gkatsev** [comment]
Hm... seems to be working for me in Chrome and Firefox.

**Comment by DetectiveBox** [comment]
> 

I used it in two projects. One is OK and the other throws the error. The code is same.

**Comment by paekjm01** [comment]
Hi,

Has it been resolved? I encountered the same issue. 
When I used the version 7.8 of videojs worked fine, but recently I upgraded to 7.20, but the same video can't play with the error message " video.es.js:100 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. MediaError {code: 3, message: 'Playback cannot continue. No available working or supported playlists.'}".

Any idea?

**Comment by gkatsev** [comment]
Code 3 basically just means that the video can't be played. Unfortunately, it isn't possible to help without a specific stream to investigate exactly what's causing playback to fail.

**Comment by paekjm01** [comment]
@gkatsev, Thank you for prompt response. One weird thing is that there is an encrypted ts file, when we play it using the version 7.10.0 or lower, it worked fine. However any version 7.10.1 or higher, we got an error message below. 

" video.es.js:100 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. MediaError {code: 3, message: 'Playback cannot continue. No available working or supported playlists.'}".

My questions are
 - Are there any noticeable changes between 7.10.0 and 7.10.1?
 - Are you saying it's most likely an the media source(ts file) issue?
 - Would you be able to investigate if I provide the media source(ts file)? 

Thank you so much for your support on this.

**Comment by venomone** [comment]
@paekjm01 How is your video encoded? Is it mpegts or fragmented mp4 aka fmp4? As I'm currently only seeing this issue with fmp4, not with mpegts ... Pretty sure that the issue is somewhere located here.

**Comment by phloxic** [comment]
@venomone - @paekjm01 talks about a TS file.

**Comment by muniv11111** [comment]
http://81.171.17.80:6878/ace/manifest.m3u8?id=ce235921dac95e1da2dd5e54673c2fecb9e806de

same (CODE:3 MEDIA_ERR_DECODE]

could you investigate this stream?

**Comment by Sylry** [comment]
I have this error code with some lists too, with 7.15.4 version

Examples:
* https://vod.canal-u.tv/hls/fire/,webinaire.fire.de.pierre.barre_61291/20210112_webinaire_fire_barre.mp4,.urlset/master.m3u8
* https://vod.canal-u.tv/hls/fire/webinaire.fire.de.pierre.barre_61291/20210112_webinaire_fire_barre.mp4/master.m3u8

**Comment by opticSquid** [comment]
I'm having the same issue. I'm trying to use `mpeg-dash`. So, my playlist file ends with `.mpd` and the segments are stored in `.m4s` files.

**Comment by CyberVy** [comment]
I got the same issue too. I found the culprit is that an audio chunk exists in the m3u8 playlist, however, the playlist should completely consist of video chunks.

BTW, Safari can still play the video, but Chrome and Firefox only throw an error below.
`Playback cannot continue. No available working or supported playlists`

I think it's not a bug of videojs.

This [m3u8 playlist](https://play.modujx16.com/20241215/HblZV6tu/5350kb/hls/index.m3u8)'s first chunk is an audio chunk. It's easy to reproduce the issue on Chrome and Firefox.

**Comment by crabhi** [comment]
Hi @CyberVy! Why should the playlist consist of video chunks?

In fact, we encountered the same issue. In our case the problem was a playlist consisting of AAC chunks. The [HLS RFC 8216](https://datatracker.ietf.org/doc/html/rfc8216) specifies that there is a list of supported formats. Our AAC chunks probably didn't have Audio Data Transport Stream framing. We solved this by wrapping AAC in MPEG-2 TS container.

**Comment by CyberVy** [comment]
@crabhi Hello.
Thanks for your information.

> Why should the playlist consist of video chunks?

I guess it's about the `tech`, and it's related with the browser.  Ensuring that they are not mixed ensures the max compatibility.

>  Our AAC chunks probably didn't have Audio Data Transport Stream framing. We solved this by wrapping AAC in MPEG-2 TS container.

The chunks of [the playlist](https://play.modujx16.com/20241215/HblZV6tu/5350kb/hls/index.m3u8) I've provided are all wrapped in the MPEG-2 TS containers, however, the player still can't work. Just like I've said above, maybe the problem you've encountered is about `tech` too.
