### ISSUE TITLE
Prefetch m3u8 video with Videojs of new version

### ISSUE THREAD

**Issue by chenbing11** [videojs/video.js#8034]
### Description

It’s normal to use v7.21.1. When video.js is upgraded to v8.0.2, an error will be reported for m3u8 video (the video is uploaded to Alibaba Cloud Computing OSS)

### Steps to reproduce

As this is a private project, so cannot share any URLs/Creds.

### Errors

Uncaught TypeError: Class constructor EventTarget$2 cannot be invoked without 'new'
    at new QualityLevelList2 (video.es.js:25503:34)
    at initPlugin (video.es.js:25657:26)
    at Player.qualityLevels2 (video.es.js:25683:10)
    at Player.basicPluginWrapper [as qualityLevels] (video.es.js:24440:29)
    at VhsHandler.setupQualityLevels_ (video.es.js:48995:34)
    at VhsHandler.src (video.es.js:48889:10)
    at Object.handleSource (video.es.js:49119:14)
    at _Tech.setSource (video.es.js:8956:30)
    at new Html5 (video.es.js:17509:12)
    at Player.loadTech_ (video.es.js:20456:18)

### What version of Video.js are you using?

8.0.2

### Video.js plugins used.

"@types/video.js": "^7.3.50"

### What browser(s) including version(s) does this occur with?

chrome 108.0.5359.98

### What OS(es) and version(s) does this occur with?

win10

**Comment by mister-ben** [comment]
ES6 classes must be used with Video.js v8. Transpiled class won't work, that's causing the `Class constructor ... cannot be invoked without 'new'` error. Looks like the issue is the qualityLevels2 plugin.

See the migration guide: https://videojs.com/guides/videojs-7-to-8/

**Comment by chenbing11** [comment]
Video.js v8. The video format suffix is ​​mp4 and the result is normal, but the m3u8 video reports an error. The framework used by the project is vue3.2+vite2, and the writing method is also the official reference demo
![image](https://user-images.githubusercontent.com/24648305/206603171-85e174de-4f75-4f14-aaae-c9ae60d184a6.png)
